### ISSUE TITLE
Scenario: .env file has both CLRF and LF line endings

### ISSUE THREAD

**Issue by abishekaditya** [mrsauravsahu/gen-env-template#25]
## Questions
1. If one of the lines was copy pasted with \r\n and other lines are \n. should it be treated as malformed or should it be fixed?

## Proposed Solution
1. use regex to split based on (\r\n|\n)

**Comment by mrsauravsahu** [comment]
Yeah, I was thinking about this too. What to do about inconsistent line endings. 
Oh, yeah, maintaining the original line endings seems like a nice solution.
